### ISSUE TITLE
ไม่สามารถทำแบบฝึกหัดได้

### ISSUE THREAD

**Issue by WidsawaD** [03376814-computer-laboratory-1/Week-06#5]
แบบฝึกหัดท้ายการทดลอง ข้อ4 ไม่สามารถหา**พื้นที่ของสี่เหลี่ยมคางหมู**ได้จาก การรับค่า กว้าง ยาว สูง ครับ

**Comment by koson** [comment]
แก้เป็นด้านขนานที่ 1  (a) และ 2 (b) ประมาณนี้ครับ
```
         a
    - - - - -      
  /          \    h     
 /            \
  ------------
          b
```

**Comment by koson** [comment]
https://th.wikihow.com/%E0%B8%84%E0%B8%B3%E0%B8%99%E0%B8%A7%E0%B8%93%E0%B8%9E%E0%B8%B7%E0%B9%89%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B8%AA%E0%B8%B5%E0%B9%88%E0%B9%80%E0%B8%AB%E0%B8%A5%E0%B8%B5%E0%B9%88%E0%B8%A2%E0%B8%A1%E0%B8%84%E0%B8%B2%E0%B8%87%E0%B8%AB%E0%B8%A1%E0%B8%B9
