### ISSUE TITLE
ไม่สามารถ pull requests ได้คับ

### ISSUE THREAD

**Issue by suprakron** [03376814-computer-laboratory-1/Week-06#6]
![image](https://user-images.githubusercontent.com/53931439/66703600-86fd1900-ed3e-11e9-9d80-169d85e2776a.png)

**Comment by koson** [comment]
เห็น pull request มาแล้ว
ตกลงยังมีปัญหาหรือเปล่าครับ

**Comment by suprakron** [comment]
ได้แล้วครับอาจารย์ขอบพระคุณมากครับ
